name: My First Workflow
on: push

jobs:
   first_job:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: List and Read files
        run: |
          echo "my first Github actions Job"
          ls -ltra
          cat README.md
      - name: Generate ASCII Artwork
        run: cowsay -f dragon "Run for cover, I am a DRAGON....RUN" >> dragon.txt
      #  #run: ls 
      #- name: read file 
      #  run: cat  README.md