name: Exploring Variables and Secrets

on:
  workflow_dispatch:  
 schedule:
    #- cron: "*/1 * * * *"
  #push

env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-nginx
  # Defining these here so they are available in all jobs
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        # Use env context for CONTAINER_REGISTRY and IMAGE_NAME
        run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Docker Login
        # Secrets must be wrapped in ${{ secrets.NAME }}
        run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Publish
        run: echo docker push ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Docker Run
        # Added dashes for the flags -d and -p
        run: echo docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest